name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean workspace
      run: |
        git clean -fdx
        rm -rf target || true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests with Maven
      env:
        CHROME_HEADLESS: true
        WEBDRIVER_CHROME_DRIVER: /usr/bin/google-chrome
      run: mvn clean verify -Dwebdriver.chrome.headless=true

    - name: Upload Serenity reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: serenity-reports
        path: target/site/serenity/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/failsafe-reports/

    - name: Upload Serenity report to Pages artifact
      uses: actions/upload-pages-artifact@v3
      if: success()
      with:
        path: target/site/serenity/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download Serenity reports
      uses: actions/download-artifact@v4
      with:
        name: serenity-reports
        path: target/site/serenity/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
#fin